# -*- coding: utf-8 -*-
"""webchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zck_OnnfRfGNBt1inm7nmW-mxW_NCAZ5

chat bot to read from blogs and sites to retrival information by user query by user using NLP,AI, and pinecorn

selenium to extract content data
deeplake to store
pinecone to get result as nlp
"""

!pip install -q deeplake pinecone selenium

#configuring selenium to retrive information from the site
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

# Set up Chrome options for headless mode and run in google chrome
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # Run Chrome in (headless mode) background without GUI
options.add_argument('--no-sandbox')  # Required for Colab
#options.add_argument('--disable-dev-shm-usage')  # Overcome limited resource problems

# Create the driver object to chrome
driver = webdriver.Chrome(options=options)

#to get the web site URL to
# Example blog URL
url = input("Enter the URL: ")

# Open the website
driver.get(url)

# Print the title of the webpage to verify obtained the link correctly
print(driver.title)

"""returned the topic correcly url linked correcly"""